### ISSUE TITLE
issue when running pub global activate svg_to_paint

### ISSUE THREAD

**Issue by Tonku** [FrancescoCatani/svg_to_paint_dart#1]
%  pub global activate svg_to_paint
Resolving dependencies... (1.2s)
The current Dart SDK version is 2.5.2.

Because pub global activate depends on svg_to_paint any which requires SDK version >=2.7.0 <3.0.0, version solving failed.

Any idea..?
Do I need to install node before this..?

**Comment by FrancescoCatani** [comment]
Surely you have to install Node. After that, you have to upgrade Dart SDK.
