### ISSUE TITLE
pub global activate svg_to_paint fails

### ISSUE THREAD

**Issue by zathras** [FrancescoCatani/svg_to_paint_dart#3]
Maybe the README should be updated?  Under install, I think it should be:
```
flutter pub global activate svg_to_paint
```
For reference:
```

billf@londo:~$ pub global activate svg_to_paint
Resolving dependencies... 
Because svg_to_paint >=1.0.8-nullsafety.0 <1.0.8 requires the Flutter SDK and
  svg_to_paint <1.0.8-nullsafety.0 depends on flutter any from sdk, svg_to_paint
  <=1.0.8-nullsafety.0 requires flutter any from sdk.
And because svg_to_paint >=1.0.8 <1.0.9-nullsafety.0 depends on flutter any
  from sdk which is forbidden, svg_to_paint <1.0.9-nullsafety.0 is forbidden.
So, because svg_to_paint >=1.0.9-nullsafety.0 requires the Flutter SDK and pub
  global activate depends on svg_to_paint any, version solving failed.

Flutter users should run `flutter pub get` instead of `pub get`.
billf@londo:~$ flutter pub global activate svg_to_paint
Resolving dependencies...
+ characters 1.1.0
+ collection 1.15.0
+ crypto 3.0.1
+ flutter 0.0.0 from sdk flutter
+ meta 1.3.0
+ path 1.8.0
+ sky_engine 0.0.99 from sdk flutter
+ svg_to_paint 1.0.9
+ typed_data 1.3.0
+ vector_math 2.1.0
Downloading svg_to_paint 1.0.9...
Precompiling executables...
Precompiled svg_to_paint:svg_to_paint.
Activated svg_to_paint 1.0.9.
```

**Comment by zathras** [comment]
Maybe I spoke too soon...  Perhaps the versioning just went sideways?  But in that case, is there a workaround, or an easy fix to make "pub global activate" work?
```
billf@londo:~/tmp/tmp$ flutter pub global run svg_to_paint
svg_to_paint 1.0.9 requires the Flutter SDK, which is unsupported for global executables.
pub finished with exit code 65
```

**Comment by FrancescoCatani** [comment]
It could be... I never had  "svg_to_paint 1.0.9 requires the Flutter SDK, which is unsupported for global executables." message. Try to run flutter doctor to check if you need to uprgrade something tool. For the command “pub global run” i have no workaround, check here for more https://dart.dev/tools/pub/cmd/pub-global .Anyway try to upgrade your Flutter sdk. I have also uploaded the new README of the package.

**Comment by FrancescoCatani** [comment]
if you still continue to have the problem and you can’t solve it in short times you can clone the project, then with your prompt go in /bin project folder (where is svg_to_paint.dart) and type:
dart run svg_to_paint.dart ... followed of arguments that you need and it will generate the files from your svg.
